version: "3.8"

services: 
  app:
    build: .
    image: app:django
    volumes:
      - ./:/django
    ports:
      - 80:8000
    container_name: django_container
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgis/postgis:15-3.3-alpine
    volumes: 
      - ./.data/db:/var/lib/postgresql/.data
    ports:
      - 5433:5432
    container_name: postgres_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: unless-stopped